### ISSUE TITLE
Handle --notebook-dir argument

### ISSUE THREAD

**Issue by eliemichel** [csiro-scientific-computing/GitCheckpoints#3]
`git` commands are called within the directory in which `ipython` is running, note the notebook's root directory.

So it fails when calling `ipython` with the `--notebook-dir` command line argument.

Here is an example of error log:

```
[E 13:28:16.865 NotebookApp] fatal: /tmp/notebooks/Untitled.ipynb : '/tmp/notebooks/Untitled.ipynb' is outside the repository
    Traceback (most recent call last):
      File "/usr/lib/python3.4/site-packages/gitcheckpoints-0.1-py3.4.egg/gitcheckpoints/gitcheckpoints.py", line 44, in create_checkpoint
        subprocess.check_output(['git', 'add', src_path], stderr=subprocess.STDOUT)
      File "/usr/lib/python3.4/subprocess.py", line 620, in check_output
        raise CalledProcessError(retcode, process.args, output=output)
    subprocess.CalledProcessError: Command '['git', 'add', '/tmp/notebooks/Untitled.ipynb']' returned non-zero exit status 128
```

**Comment by smoskwa** [comment]
I should be able to look at this in the next couple days but if you're keen, just try modifying it with something like this:

``` python
subprocess.check_output(['git', 'init'], stderr=subprocess.STDOUT, cwd=self.parent.parent.notebook_dir)
```

Probably won't need much else, I think the other subprocess calls probably specify full file paths to operate on

**Comment by eliemichel** [comment]
Ok, I was missing the `self.parent.parent.notebook_dir`. Isn't there a more transparent way to get the `NotebookApp.notebook_dir` parameters?

And I am not sure absolute paths are enough for other commands:

```
$ cd /tmp
/tmp$ mkdir a; cd a; git init
Empty Git Repository initialized in /tmp/a/.git/
/tmp/a$ touch b; git add b
/tmp/a$ cd /tmp; git add a/b
fatal: Not a git repository (or any parent up to mount point /tmp)
```

**Comment by eliemichel** [comment]
Also, what are `GitCheckpoints._root_dir_default()` and `GitCheckpoints.root_dir` used for?

I see a call to `self.parent.root_dir` that might be replaced with `self.parent.parent.notebook_dir` but it is actually never called…

_edit: Well, it may be called from the parent. Didn't though about it at first, sorry._
